services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flow_data_platform

    networks:
      - api-network

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - ./src:/app/src 
    networks:
      - api-network

  kafka-container:
    image: wurstmeister/kafka:2.12-2.8.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-container:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://
    networks:
      - api-network
    

networks:
  api-network:
    driver: bridge